version: '3.4'

services:
    users-service:
        container_name: users-service
        build: .
        volumes:
            - '.:/usr/src/app'
        ports:
            - 5050:5000
        environment:
            - APP_SETTINGS=project.config.DevelopmentConfig
